name: my_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.18
  dio: ^4.0.0
  # dio_http_cache: ^0.3.0
  pretty_dio_logger: ^1.1.1
  logger: ^1.2.2
  intl: ^0.17.0
  simple_animations: ^5.0.0+3
  flutter_bloc: ^8.1.2
  json_annotation: ^4.6.0
  build_runner: ^2.1.7
  sliding_up_panel: ^2.0.0+1
  image_picker: ^0.8.7
  image_cropper: ^3.0.2
  photo_manager: ^2.5.2
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.1
  meta: ^1.8.0
  path_provider: ^2.0.14
  pdf: ^3.10.1
  flutter_pdfview: ^1.3.0
  share_plus: ^6.3.2
  permission_handler: ^10.2.0
  flutter_svg: ^1.1.6
  sqflite: ^2.2.6
  path: ^1.8.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: any
  dart_code_metrics: any
  flutter_lints: ^2.0.1
  stream_transform: ^2.1.0
  json_serializable: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: EncodeSans
      fonts:
        - asset: assets/fonts/EncodeSans-Regular.ttf

        - asset: assets/fonts/EncodeSans-Thin.ttf
          weight: 100

        - asset: assets/fonts/EncodeSans-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/EncodeSans-Light.ttf
          weight: 300

        - asset: assets/fonts/EncodeSans-Medium.ttf
          weight: 500

        - asset: assets/fonts/EncodeSans-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/EncodeSans-Bold.ttf
          weight: 700

        - asset: assets/fonts/EncodeSans-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/EncodeSans-Black.ttf
          weight: 900
